/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RoomsIdRouteImport } from './routes/rooms/$id'
import { Route as AdminRoomsIndexRouteImport } from './routes/admin/rooms/index'
import { Route as AdminRoomsNewRouteImport } from './routes/admin/rooms/new'
import { Route as AdminRoomsIdEditRouteImport } from './routes/admin/rooms/$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const RoomsIdRoute = RoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsIndexRoute = AdminRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomsNewRoute = AdminRoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomsIdEditRoute = AdminRoomsIdEditRouteImport.update({
  id: '/rooms/$id/edit',
  path: '/rooms/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/admin/rooms': typeof AdminRoomsIndexRoute
  '/admin/rooms/$id/edit': typeof AdminRoomsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/admin/rooms': typeof AdminRoomsIndexRoute
  '/admin/rooms/$id/edit': typeof AdminRoomsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/admin/rooms/': typeof AdminRoomsIndexRoute
  '/admin/rooms/$id/edit': typeof AdminRoomsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/rooms/$id'
    | '/admin/'
    | '/admin/rooms/new'
    | '/admin/rooms'
    | '/admin/rooms/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/rooms/$id'
    | '/admin'
    | '/admin/rooms/new'
    | '/admin/rooms'
    | '/admin/rooms/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/rooms/$id'
    | '/admin/'
    | '/admin/rooms/new'
    | '/admin/rooms/'
    | '/admin/rooms/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RoomsIdRoute: typeof RoomsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms/': {
      id: '/admin/rooms/'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rooms/new': {
      id: '/admin/rooms/new'
      path: '/rooms/new'
      fullPath: '/admin/rooms/new'
      preLoaderRoute: typeof AdminRoomsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rooms/$id/edit': {
      id: '/admin/rooms/$id/edit'
      path: '/rooms/$id/edit'
      fullPath: '/admin/rooms/$id/edit'
      preLoaderRoute: typeof AdminRoomsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRoomsNewRoute: typeof AdminRoomsNewRoute
  AdminRoomsIndexRoute: typeof AdminRoomsIndexRoute
  AdminRoomsIdEditRoute: typeof AdminRoomsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminRoomsNewRoute: AdminRoomsNewRoute,
  AdminRoomsIndexRoute: AdminRoomsIndexRoute,
  AdminRoomsIdEditRoute: AdminRoomsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RoomsIdRoute: RoomsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
